### PR TITLE
Changed converting method to regex.

### PR DESCRIPTION
**Pull request by iMoD1998**
Hi, I changed the way you are converting the GXT entries with regex also removed waiting for the enter key at the end.

### CODE REVIEW

**Comment by Starystars67** [comment]
Hey, thanks for your commit request. can I ask how are you making the system pause at the end of processing? I had it set up with the waiting for key entry to allow the user to see that all was read successfully otherwise the window closed automatically.

**Comment by Starystars67** [comment]
However great use of regex, I'm not quite sure why I didn't use that!

**Comment by iMoD1998** [comment]
Hey sorry I'm a bit late. I just removed it because if you want to see the output you can start a cmd window first it wont automatically close. However, some people might not know this so i guess i should add it back.

**Comment by Starystars67** [comment]
@iMoD1998 Yeah that was what i thought and was why i compiled it into an exe. let me know when its back and ill pull it in and rerelease

**Pull request merged**
